source 'http://rubygems.org'

gem 'activerecord', '6.1.7.1', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'

gem 'sinatra'
gem 'sqlite3', '~>1.3.6'
gem 'tux'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'json'
gem 'pry'
gem 'bcrypt'
gem 'rack-flash3'
gem 'sinatra-flash'